<NBackGame>:
    canvas:
        Rectangle:
            pos: self.center_x - 5, 0 #Subtract half the size to center the line
            size: 10, self.height

    Label:
        font_size: 70
        center_x: root.width / 4 # Quarter way across screen
        top: root.top - 50 # 50 pixels from the top
        text: "0"

    Label:
        font_size: 70
        center_x: root.width * 3/ 4 # Quarter from edge screen
        top: root.top - 50 # 50 pixels from the top
        text: "0"